# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod "Qiniu", "~> 7.0"
pod 'ASMediaFocusManager'
target 'chichichi' do

end

target 'chichichiTests' do

end

